version: "3"
services:
  geth-bootnode:
    hostname: geth-bootnode
    environment:
      - nodekeyhex=08f0e1dee5c1b4645f3331a566009e41a4514b6cd28656d63d0449ecf812812b #Needs to be fix, so that the miners know the resulting enode id
    build:
      context: ./bootnode
    ports:
      - 30301:30301/udp
    networks:
      chainnet:
        ipv4_address: 172.25.0.101 # The miners need to know the IP address later on

  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    depends_on:
      - geth-bootnode
    environment:
      - address=0x92ff04eccfff536dbe51eec8b7127d023ff3a6aa #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./miner
      args:
        privatekey: 5aaee3e8dd3453e718f4c11976797b2b680e9ef0be4ccf785c83919c168f3be6 # Please don't do something like this in production, okay?
        password: pass
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address

  geth-dev-miner-2:
    hostname: geth-dev-miner-2
    depends_on:
      - geth-bootnode
    environment:
      - address=0xe1c4fe1d8b64045c217a95f4732a2923a471c766 #derived from the private key which is passed in the args
      - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=172.25.0.101
    build:
      context: ./miner
      args:
        privatekey: 8822884d2fb4c5709b3b6c502f4a95c1c3d4d0dcd56dc0dba7b33ad46f3b2eed
        password: word
    container_name: geth-miner-2
    volumes:
     - eth-data-2:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.104

  geth-dev-node:
     hostname: geth-dev-node
     depends_on:
       - geth-dev-miner-2
     environment:
       - address=0xe1c4fe1d8b64045c217a95f4732a2923a471c766 #derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./node
       args:
         privatekey: 8822884d2fb4c5709b3b6c502f4a95c1c3d4d0dcd56dc0dba7b33ad46f3b2eed
         password: word
     container_name: geth-node
     ports:
       - 8545:8545
       - 8546:8546
     healthcheck:
       test: wget http://localhost:8545
       interval: 2s
       timeout: 5s
       retries: 30
     volumes:
      - eth-data-3:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.110

  geth-dev-swarm-1:
     hostname: geth-dev-swarm-1
     depends_on:
       - geth-dev-node
     environment:
       - address=92ff04eccfff536dbe51eec8b7127d023ff3a6aa #derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./swarm
       args:
         privatekey: 5aaee3e8dd3453e718f4c11976797b2b680e9ef0be4ccf785c83919c168f3be6
         password: pass
     container_name: geth-swarm-1
     ports:
       - 8500:8500
       - 30399:30399/udp
     volumes:
      - eth-data-4:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.111

  geth-dev-swarm-2:
     hostname: geth-dev-miner-3
     depends_on:
       - geth-dev-node
     environment:
       - address=e1c4fe1d8b64045c217a95f4732a2923a471c766 #derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./swarm
       args:
         privatekey: 8822884d2fb4c5709b3b6c502f4a95c1c3d4d0dcd56dc0dba7b33ad46f3b2eed
         password: pass
     container_name: geth-swarm-2
     ports:
       - 8501:8500
       - 30340:30399/udp
     volumes:
      - eth-data-5:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.112

  geth-explorer:
    hostname: geth-explorer
    depends_on:
      - geth-dev-node
    ports:
      - 8080:8080
    build:
      context: ./explorer
    container_name: geth-explorer
    networks:
      chainnet:
        ipv4_address: 172.25.0.125

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
  eth-data-2:
  eth-data-3:
  eth-data-4:
  eth-data-5:
  eth-data-6:
